spring:
  data:
    mongodb:
      host: 172.17.0.2
      database: sushi
  messages:
    basename: locale/messages
  profiles:
    active: production

logging:
  level:
    org.springframework.security: DEBUG
      
---

spring:
    profiles: integration-test, mobile-integration-test
    data:
      mongodb:
        host: 172.17.0.2
        database: test-sushi
      
    
    